name: ddmp
channels:
  - defaults
  - pytorch
  - open3d-admin
dependencies:
  - python=3.7
  - cython
  - pytorch=1.7.0
  - cudatoolkit=11.0
  - numpy
  - matplotlib
  - tensorflow
  - tensorboard
  - open3d
  - pip
  - pip:
    - pyyaml
    - addict
    - plyfile
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch-scatter==2.0.7
    - torch-sparse==0.6.9
    - torch-cluster==1.5.9
    - torch-spline-conv==1.2.1
    - torch-geometric==1.7.1
    - pymeshlab==2021.10
    - tqdm==4.61.1
    - scikit-learn==0.24.2
    - torchvision==0.8.1+cu110
    - torchaudio==0.7.0 
