name: ddmp
channels:
  - defaults
  - pytorch
  - open3d-admin
dependencies:
  - python=3.7
  - cython
  - pytorch=1.7.0
  - cudatoolkit=11.0
  - numpy
  - matplotlib
  - tensorflow
  - tensorboard
  - open3d
  - pip
